# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				villager = true
				salmon = true
				wandering_trader = true
				donkey = true
				cow = true
				boat = true
				item_frame = true
				pig = true
				horse = true
				bat = true
				leash_knot = true
				painting = true
				cat = true
				rabbit = true
				glow_squid = true
				armor_stand = true
				glow_item_frame = false
				squid = true
				sheep = true
				player = true

